### ISSUE TITLE
[bug] Yaml Flow Scalars - Plain (multiline) not supported

### ISSUE THREAD

**Issue by srealmoreno** [EndBug/label-sync#142]
When using a [Flow Scalars plain](https://yaml-multiline.info/) the parser fails.

My `labels.yml`

```yaml
- name: breaking-change 💥
  color: D93F0B
  description:
    A change that changes the API or breaks backward compatibility for
    users.

- name: bug 🐞
  color: d73a4a
  description: Inconsistencies or issues which will cause a problem for users or
    implementors.

- name: ci 🤖
  color: "536266"
  description: Work that improves the continuous integration.
```

Error:

![image](https://user-images.githubusercontent.com/50985135/173179283-f197d226-d4b9-49c3-a53f-af6f8eda1f82.png)

Apparently there is already an open issue in `yamljs` [#112](https://github.com/jeremyfa/yaml.js/issues/112) [#141](https://github.com/jeremyfa/yaml.js/issues/141) but it has not been maintained
